id: P009618
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23809
  title: གྲུབ་དབང་ཤཱཀྱ་ཤྲཱིའི་རྣམ་ཐར་མེ་ཏོག་ཕྲེང་བ།
  author: ''
  volumes:
    537173d286204c05a019db084380603f:
      image_group_id: I2831
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
