id: I869B066F
legacy_id: P009618
ocr_import_info:
  bdrc_scan_id: W23809
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T22:21:35'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:46:00.196390+00:00'
last_modified: 2022-09-02 12:46:04.518045
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23809
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23809
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་དབང་ཤཱཀྱ་ཤྲཱིའི་རྣམ་ཐར་མེ་ཏོག་ཕྲེང་བ།
  author: ཀཿ་ཐོག་སི་ཏུ ༠༣་ཆོས་ཀྱི་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9189170958086621
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2831
      total_pages: 218
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2831.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9189170958086621
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
